apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: "NOMA-DO-USUARIO-AQUI"
  POSTGRES_PASSWORD: "SUA-SENHA-AQUI"
  POSTGRES_DB: "NOME-DO-BANCO-AQUI"
  DATABASE_URL: "postgresql://USUARIO:SENHA@postgres-service:5432/apidb"